// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PusulaApp.Data;

#nullable disable

namespace PusulaApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240921121516_TableHeadUpdate")]
    partial class TableHeadUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PusulaApp.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Price = 1500.00m,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductID = 2,
                            Price = 25.00m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 3,
                            Price = 45.00m,
                            ProductName = "Keyboard"
                        });
                });

            modelBuilder.Entity("PusulaApp.Models.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SaleID");

                    b.HasIndex("ProductID");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleID = 1,
                            ProductID = 1,
                            Quantity = 2,
                            SaleDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleID = 2,
                            ProductID = 2,
                            Quantity = 5,
                            SaleDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleID = 3,
                            ProductID = 1,
                            Quantity = 1,
                            SaleDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleID = 4,
                            ProductID = 3,
                            Quantity = 3,
                            SaleDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleID = 5,
                            ProductID = 2,
                            Quantity = 7,
                            SaleDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SaleID = 6,
                            ProductID = 3,
                            Quantity = 2,
                            SaleDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PusulaApp.Models.Sale", b =>
                {
                    b.HasOne("PusulaApp.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PusulaApp.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
